name: Main workflow
on: [push]
jobs:
  setup:
    name: Setup
    runs-on: macOS-latest
    steps:
      - name: Set Node.js 10.x
        uses: actions/setup-node@v1.1.1
        with:
          version: 10.x
      - name: yarn install
        run: yarn install
       
  test:
    name: Test
    needs: [setup]
    runs-on: macOS-latest
    steps:
    - name: Run tests
      run: yarn test

