name: Main workflow
on: [push]
jobs:  
  test:
    name: Test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set Node.js 10.x
      uses: actions/setup-node@v1.1.1
      with:
        version: 10.x
    - name: yarn install
      run: yarn install
    - name: Test
      env:
      - CI: true
      run: yarn test

